#MARKSHEET 
print(" "*15 + "MARKSHEET" )
print("-"*40)
print(" "*8 + "SUBJECT"+" "*10+"MARKS")
print("-"*40)
print(" "*8 +"ENGLISH")
print(" "*8 +"MATHS")
print(" "*8 +"SCIENCE")
print("-"*40)
print(" "*8 +"PERCENTAGE"+" "*7+"TOTAL")